server:
  port: ${PORT:0}
  
spring:
  application:
    name: account-app

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://54.164.127.133:3307/hr
    username: root
    password: root 
  boot:
    admin:
      client:
        url: http://3.83.48.158:8888/admin
        instance:
          service-base-url: http://3.83.48.158:8888/admin
  
 
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://3.83.48.158:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'


      
    